# Generated by Django 5.2.7 on 2025-10-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_orguser_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orguser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
    ]
