services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: django_stripe_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"

    environment: # unsafe, .env better but for now it gets the work done
      DEBUG: "True"
      SECRET_KEY: "django-insecure-%qks8s3i@7f073ad_i#=qs(a(7&)@v_l524)e3izi0ci91)y5z"
      POSTGRES_DB: django_stripe_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      STRIPE_PUBLIC_KEY: "pk_test_51SCbLXQDpXyLVhRG8pIkf7oUWiSGbWWyqIZ8WUW6ddnGC4PshQ7Q5Hl5TMdf1bWIMgtwFilGLIKVEsC4aaNIM51n007DQMUMqa"
      STRIPE_SECRET_KEY: "sk_test_51SCbLXQDpXyLVhRGGlJxtkiHXAFAPlnM76cbebJA9CqccCgF8mO80mu3sG8pV87OrqhXizm3IFPYCfRVhr1epAej00XohoN5y2"
    depends_on:
      - db

volumes:
  postgres_data:
